// Code generated by MockGen. DO NOT EDIT.
// Source: L4.3/internal/repo (interfaces: EventRepo)

package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "L4.3/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
}

type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

func (m *MockEventRepo) Create(ctx context.Context, event domain.Event) (domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockEventRepoMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRepo)(nil).Create), ctx, event)
}

func (m *MockEventRepo) Update(ctx context.Context, id int64, event domain.Event) (domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, event)
	ret0, _ := ret[0].(domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockEventRepoMockRecorder) Update(ctx, id, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventRepo)(nil).Update), ctx, id, event)
}

func (m *MockEventRepo) Delete(ctx context.Context, id int64) (domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockEventRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventRepo)(nil).Delete), ctx, id)
}

func (m *MockEventRepo) ListForPeriod(ctx context.Context, userID int64, from time.Time, to time.Time) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForPeriod", ctx, userID, from, to)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockEventRepoMockRecorder) ListForPeriod(ctx, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForPeriod", reflect.TypeOf((*MockEventRepo)(nil).ListForPeriod), ctx, userID, from, to)
}

func (m *MockEventRepo) ArchiveOld(ctx context.Context, before time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveOld", ctx, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockEventRepoMockRecorder) ArchiveOld(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveOld", reflect.TypeOf((*MockEventRepo)(nil).ArchiveOld), ctx, before)
}

func (m *MockEventRepo) ListPendingReminders(ctx context.Context, now time.Time) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingReminders", ctx, now)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockEventRepoMockRecorder) ListPendingReminders(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingReminders", reflect.TypeOf((*MockEventRepo)(nil).ListPendingReminders), ctx, now)
}

func (m *MockEventRepo) MarkReminded(ctx context.Context, id int64, remindedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkReminded", ctx, id, remindedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventRepoMockRecorder) MarkReminded(ctx, id, remindedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReminded", reflect.TypeOf((*MockEventRepo)(nil).MarkReminded), ctx, id, remindedAt)
}
